version: "3"
services:
  traefik:
    image: traefik:v2.8
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./custom/:/custom/:ro
      - ./data/acme.json:/acme.json # chmod 600 root:root