api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: ":80"
    http:
# who get crt
      tls:
        certResolver: myresolver
# redirect to https
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

  mysql:
    address: ":1532"

  dns:
    address: ":53/udp"

providers:
  file:
    directory: /custom
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      email: [email]
      storage: /acme.json
      tlsChallenge: true